### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by sanjayankur31** [grabbles/grabbit#72]
The tests currently fail. I've tested it out in a Fedora build, and in a fresh virtual environment:

```bash
(ins)[asinha@ankur  grabbit(master=)]$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

(ins)[asinha@ankur  grabbit(master=)]$ python3 -m venv ~/dump/grabbit-virt
(ins)[asinha@ankur  grabbit(master=)]$ source ~/dump/grabbit-virt/bin/activate
(ins)(grabbit-virt) [asinha@ankur  grabbit(master=)]$ python setup.py install
running install
running bdist_egg
running egg_info
creating grabbit.egg-info
writing grabbit.egg-info/PKG-INFO
writing dependency_links to grabbit.egg-info/dependency_links.txt
writing top-level names to grabbit.egg-info/top_level.txt
writing manifest file 'grabbit.egg-info/SOURCES.txt'
reading manifest file 'grabbit.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'grabbit.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/grabbit
copying grabbit/_version.py -> build/lib/grabbit
copying grabbit/core.py -> build/lib/grabbit
copying grabbit/utils.py -> build/lib/grabbit
copying grabbit/__init__.py -> build/lib/grabbit
creating build/lib/grabbit/external
copying grabbit/external/six.py -> build/lib/grabbit/external
copying grabbit/external/__init__.py -> build/lib/grabbit/external
copying grabbit/external/inflect.py -> build/lib/grabbit/external
creating build/lib/grabbit/extensions
copying grabbit/extensions/hdfs.py -> build/lib/grabbit/extensions
copying grabbit/extensions/__init__.py -> build/lib/grabbit/extensions
copying grabbit/extensions/writable.py -> build/lib/grabbit/extensions
UPDATING build/lib/grabbit/_version.py
set build/lib/grabbit/_version.py to '0.2.0'
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/grabbit
creating build/bdist.linux-x86_64/egg/grabbit/external
copying build/lib/grabbit/external/six.py -> build/bdist.linux-x86_64/egg/grabbit/external
copying build/lib/grabbit/external/__init__.py -> build/bdist.linux-x86_64/egg/grabbit/external
copying build/lib/grabbit/external/inflect.py -> build/bdist.linux-x86_64/egg/grabbit/external
copying build/lib/grabbit/_version.py -> build/bdist.linux-x86_64/egg/grabbit
copying build/lib/grabbit/core.py -> build/bdist.linux-x86_64/egg/grabbit
creating build/bdist.linux-x86_64/egg/grabbit/extensions
copying build/lib/grabbit/extensions/hdfs.py -> build/bdist.linux-x86_64/egg/grabbit/extensions
copying build/lib/grabbit/extensions/__init__.py -> build/bdist.linux-x86_64/egg/grabbit/extensions
copying build/lib/grabbit/extensions/writable.py -> build/bdist.linux-x86_64/egg/grabbit/extensions
copying build/lib/grabbit/utils.py -> build/bdist.linux-x86_64/egg/grabbit
copying build/lib/grabbit/__init__.py -> build/bdist.linux-x86_64/egg/grabbit
byte-compiling build/bdist.linux-x86_64/egg/grabbit/external/six.py to six.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/grabbit/external/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/grabbit/external/inflect.py to inflect.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/grabbit/_version.py to _version.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/grabbit/core.py to core.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/grabbit/extensions/hdfs.py to hdfs.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/grabbit/extensions/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/grabbit/extensions/writable.py to writable.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/grabbit/utils.py to utils.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/grabbit/__init__.py to __init__.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying grabbit.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying grabbit.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying grabbit.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying grabbit.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
grabbit.external.__pycache__.six.cpython-36: module references __path__
creating dist
creating 'dist/grabbit-0.2.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing grabbit-0.2.0-py3.6.egg
creating /home/asinha/dump/grabbit-virt/lib/python3.6/site-packages/grabbit-0.2.0-py3.6.egg
Extracting grabbit-0.2.0-py3.6.egg to /home/asinha/dump/grabbit-virt/lib/python3.6/site-packages
Adding grabbit 0.2.0 to easy-install.pth file

Installed /home/asinha/dump/grabbit-virt/lib/python3.6/site-packages/grabbit-0.2.0-py3.6.egg
Processing dependencies for grabbit==0.2.0
Finished processing dependencies for grabbit==0.2.0
(ins)(grabbit-virt) [asinha@ankur  grabbit(master=)]$ python setup.py test
running test
Searching for pytest>=3.3.0
Reading https://pypi.org/simple/pytest/
Downloading https://files.pythonhosted.org/packages/11/c4/cfb5f51f401cd54bbaaacff530c96827422a29dca2683ff314e4938444c9/pytest-3.6.2-py2.py3-none-any.whl#sha256=90898786b3d0b880b47645bae7b51aa9bbf1e9d1e4510c2cfd15dd65c70ea0cd
Best match: pytest 3.6.2
Processing pytest-3.6.2-py2.py3-none-any.whl
Installing pytest-3.6.2-py2.py3-none-any.whl to /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs
writing requirements to /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs/pytest-3.6.2-py3.6.egg/EGG-INFO/requires.txt

Installed /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs/pytest-3.6.2-py3.6.egg
Searching for six>=1.10.0
Reading https://pypi.org/simple/six/
Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl#sha256=832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb
Best match: six 1.11.0
Processing six-1.11.0-py2.py3-none-any.whl
Installing six-1.11.0-py2.py3-none-any.whl to /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs

Installed /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs/six-1.11.0-py3.6.egg
Searching for py>=1.5.0
Reading https://pypi.org/simple/py/
Downloading https://files.pythonhosted.org/packages/f3/bd/83369ff2dee18f22f27d16b78dd651e8939825af5f8b0b83c38729069962/py-1.5.4-py2.py3-none-any.whl#sha256=e31fb2767eb657cbde86c454f02e99cb846d3cd9d61b318525140214fdc0e98e
Best match: py 1.5.4
Processing py-1.5.4-py2.py3-none-any.whl
Installing py-1.5.4-py2.py3-none-any.whl to /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs

Installed /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs/py-1.5.4-py3.6.egg
Searching for pluggy<0.7,>=0.5
Reading https://pypi.org/simple/pluggy/
Downloading https://files.pythonhosted.org/packages/ba/65/ded3bc40bbf8d887f262f150fbe1ae6637765b5c9534bd55690ed2c0b0f7/pluggy-0.6.0-py3-none-any.whl#sha256=e160a7fcf25762bb60efc7e171d4497ff1d8d2d75a3d0df7a21b76821ecbf5c5
Best match: pluggy 0.6.0
Processing pluggy-0.6.0-py3-none-any.whl
Installing pluggy-0.6.0-py3-none-any.whl to /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs

Installed /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs/pluggy-0.6.0-py3.6.egg
Searching for more-itertools>=4.0.0
Reading https://pypi.org/simple/more-itertools/
Downloading https://files.pythonhosted.org/packages/85/40/90c3b0393e12b9827381004224de8814686e3d7182f9d4182477f600826d/more_itertools-4.2.0-py3-none-any.whl#sha256=6703844a52d3588f951883005efcf555e49566a48afd4db4e965d69b883980d3
Best match: more-itertools 4.2.0
Processing more_itertools-4.2.0-py3-none-any.whl
Installing more_itertools-4.2.0-py3-none-any.whl to /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs
writing requirements to /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs/more_itertools-4.2.0-py3.6.egg/EGG-INFO/requires.txt

Installed /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs/more_itertools-4.2.0-py3.6.egg
Searching for attrs>=17.4.0
Reading https://pypi.org/simple/attrs/
Downloading https://files.pythonhosted.org/packages/41/59/cedf87e91ed541be7957c501a92102f9cc6363c623a7666d69d51c78ac5b/attrs-18.1.0-py2.py3-none-any.whl#sha256=4b90b09eeeb9b88c35bc642cbac057e45a5fd85367b985bd2809c62b7b939265
Best match: attrs 18.1.0
Processing attrs-18.1.0-py2.py3-none-any.whl
Installing attrs-18.1.0-py2.py3-none-any.whl to /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs
writing requirements to /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs/attrs-18.1.0-py3.6.egg/EGG-INFO/requires.txt

Installed /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs/attrs-18.1.0-py3.6.egg
Searching for atomicwrites>=1.0
Reading https://pypi.org/simple/atomicwrites/
Downloading https://files.pythonhosted.org/packages/0a/e8/cd6375e7a59664eeea9e1c77a766eeac0fc3083bb958c2b41ec46b95f29c/atomicwrites-1.1.5-py2.py3-none-any.whl#sha256=a24da68318b08ac9c9c45029f4a10371ab5b20e4226738e150e6e7c571630ae6
Best match: atomicwrites 1.1.5
Processing atomicwrites-1.1.5-py2.py3-none-any.whl
Installing atomicwrites-1.1.5-py2.py3-none-any.whl to /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs

Installed /home/asinha/Documents/02_Code/00_repos/01_others/grabbit/.eggs/atomicwrites-1.1.5-py3.6.egg
running egg_info
writing grabbit.egg-info/PKG-INFO
writing dependency_links to grabbit.egg-info/dependency_links.txt
writing top-level names to grabbit.egg-info/top_level.txt
reading manifest file 'grabbit.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'grabbit.egg-info/SOURCES.txt'
running build_ext
six (unittest.loader._FailedTest) ... ERROR
inflect (unittest.loader._FailedTest) ... ERROR
hdfs (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: six (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: six
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'grabbit.external.six.six'


======================================================================
ERROR: inflect (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: inflect
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'grabbit.external.six.inflect'


======================================================================
ERROR: hdfs (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: hdfs
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/asinha/Documents/02_Code/00_repos/01_others/grabbit/grabbit/extensions/hdfs.py", line 3, in <module>
    from hdfs import Config
ModuleNotFoundError: No module named 'hdfs'


----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (errors=3)
Test failed: <unittest.runner.TextTestResult run=3 errors=3 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=3 errors=3 failures=0>
```

The last test is fixed when one installs `hdfs`, so that maybe needs to be added to the `setup.py` file. Not too sure about the other two tests yet.

Thanks :)

**Comment by tyarkoni** [comment]
Is it necessary to use unittest? These tests should all pass with py.test, which is what we test with. I'm not sure why the imports are failing with unittest. The hdfs tests probably won't pass on any platform, so it's probably for the best that they not run.

**Comment by tyarkoni** [comment]
@sanjayankur31 I'm going to close this, as the solution is to switch to py.test for testing. If for some reason you can't use py.test, let me know, but otherwise I don't think it's worth the effort to rewrite the tests just for unittest.

**Comment by sanjayankur31** [comment]
Yeh, that's OK. I'll switch to py.test too. Thanks!
